# Setup
name:         Hardware security
tagline:      Lab
baseurl:      "https://saichandsamudrala2022.github.io/course.github.io/"
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
